### ISSUE TITLE
video

### ISSUE THREAD

**Issue by pizzav-xyz** [JustAlittleWolf/ConnectedTexturesGenerator#1]
can you make a video tutorial on how to do this

**Comment by JustAlittleWolf** [comment]
No, I can explain it to you on discord tho if you want to

**Comment by pizzav-xyz** [comment]
> No, I can explain it to you on discord tho if you want to

discord is private and censored

**Comment by JustAlittleWolf** [comment]
Ok, is your problem solved then?

**Comment by pizzav-xyz** [comment]
> Ok, is your problem solved then?

no i sent my discord so you can help me on discord
