### ISSUE TITLE
Blank textures

### ISSUE THREAD

**Issue by o9zs** [JustAlittleWolf/ConnectedTexturesGenerator#2]
All of the textures in the resulting folder come out completely blank. This is the image I'm using:
![cobblestone](https://github.com/JustAlittleWolf/ConnectedTexturesGenerator/assets/99386990/70ce58c5-4973-4bcb-b40d-323854291a52)
I have Pillow installed, I'm using Python 3.11.5.

**Comment by JustAlittleWolf** [comment]
Hey, is it possible that you input picture is stored as an indexed png? When downloading yours it shows up as one (although that might just be imgur) and converting it to a RGB image fixed the empty output for me.

Example of how to do this in gimp:
![image](https://github.com/JustAlittleWolf/ConnectedTexturesGenerator/assets/54244277/1da9213a-1490-4749-b2fd-771dbaa7ba67)

I don't have a lot of time for this project unfortunately so a fix to also accept indexed images would take a while.

**Comment by o9zs** [comment]
That was the problem, thank you so much!
